# Generated by Django 2.0.1 on 2018-01-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='card_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='card_title',
            new_name='title',
        ),
    ]
